### ISSUE TITLE
Notification for Japanese edtion of template hierarchy

### ISSUE THREAD

**Issue by atachibana** [pressupinc/wphierarchy#10]
Hi Rami
I am a codex Japanese translator and localized your template hierarchy chart and web site.
Thank you for you cool and beautiful image and dynamic site.

Ref: http://unofficialtokyo.com/wordpress-template-hierarchy
Ref: http://wpdocs.sourceforge.jp/%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB:wp-template-hierarchy.jpg

**Comment by ramiabraham** [comment]
Hi @atachibana - sorry for the delay; I missed this notification. This is really great! I've added a link to this on wphierarchy.com, as well as started localization for the wphierarchy.com site.

There are now `gettext` wrappers in place for all of the areas you've translated; I'll be adding example translation files shortly as well.

**Comment by atachibana** [comment]
Hi @ramiabraham - thank you so much. I just started enhancement for singular.php but it seems that I don't need any work except just waiting your enhancement. :-)

**Comment by ramiabraham** [comment]
Hi @atachibana - yes, I added singular.php earlier this week; you should be able to pull in the new changes and specify a language file for Japanese translation. I'll be adding localization this week.

**Comment by davidbhayes** [comment]
For clean-house reasons, I'm going to close this issue. I think #16 is a better bucket for it. 

@atachibana are you still trying to keep an up-to-date Japanese version? Does the repo in it's current state adequate address those needs?

**Comment by atachibana** [comment]
@davidbhayes 
I am very sorry for the no response. I didn't notice your mentions...
Yes, I would like to keep updates.
I will fork V2 and re-think the design. But for my laziness, I may take dirty way by overwrites the English text by Japanese...

**Comment by davidbhayes** [comment]
@atachibana No worries. Feel free to fork, but I'd also welcome your thoughts on #16 about how best to handle internationalization of this project.
