### ISSUE TITLE
Remove comments-popup.php; deprecated in 4.5

### ISSUE THREAD

**Issue by jtsternberg** [pressupinc/wphierarchy#19]
Just a heads up really.

> ...A time when we can remove comment popup functionality from WordPress. If this breaks the internet, I'll eat my hat.

[https://core.trac.wordpress.org/ticket/28617#comment:14](https://core.trac.wordpress.org/ticket/28617#comment:14)

**Comment by ramiabraham** [comment]
thanks @jtsternberg, will get this removed #latestreplyever

**Comment by davidbhayes** [comment]
Removed by 237b79d10b6e12bfab1513228af078aca3d970b5, 81a2ba6d44172c728e36dbc3a58da70a67bbfadd
