### ISSUE TITLE
Correct the single attachment template hierarchy

### ISSUE THREAD

**Issue by johnbillion** [pressupinc/wphierarchy#26]
The template hierarchy for single attachment pages is actually more complex than the current diagram shows. If an `attachment.php` file isn't present, the hierarchy moves onto that for single posts.

In addition, the mime type hierarchy was reversed back in WordPress 4.3, so the diagram needs updating.

The correct hierarchy for a single attachment page is:
1. `$mimetype-$subtype.php` (note the dash instead of underscore)
2. `$subtype.php`
3. `$mimetype.php`
4. `attachment.php`
5. `single-$posttype-$slug.php`
6. `single-$posttype.php`
7. `single.php`
8. `singular.php`

**Comment by ramiabraham** [comment]
Thanks @johnbillion will get this in shortly.

**Comment by davidbhayes** [comment]
Have resolved the issue that the first three pieces of that chain were incorrectly ordered. Resolving the issue of media doubling-back into the single post structure is harder. Can WordPress just change how it works? ;p

I think I just need an elaborate curve, I'm just not especially blessed at SVG curve drawing...

**Comment by johnbillion** [comment]
Yeah I think the double-backing can be ignored for now. It's not worth over-complicating the diagram for this.
