### ISSUE TITLE
paged.php no longer exists

### ISSUE THREAD

**Issue by johnbillion** [pressupinc/wphierarchy#28]
Since WordPress 4.7, `paged.php` is no longer part of the template hierarchy. It just needs to be removed entirely from the hierarchy diagram.

https://make.wordpress.org/core/2016/09/09/new-functions-hooks-and-behaviour-for-theme-developers-in-wordpress-4-7/

**Comment by davidbhayes** [comment]
Thank you for reporting @johnbillion, should be fixed!
